name: GitHub Actions pytest
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        - run: pip install -r requirements.txt
        - run: python -m pytest
        - run: echo "The job was successful"